### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by rojvv**

### CODE REVIEW

**Comment by sinaahmadi** [comment]
Thanks very much, @rojserbest!

**Comment by rojvv** [comment]
Mh you think like PRs are suggestions that can't be merged or you like to be the only contributor in your projects?

Thank you too, anyway. But you forgot to correct "Mozilla", it is the name of the company, not the browser.

**Comment by sinaahmadi** [comment]
@rojserbest Thanks. I have no problem merging pull requests and I appreciate your scrutiny about these projects 🙂 However, as a general rule, I personally believe in a pull request that improves the technical aspects of the tool. That doesn't, of course, mean that reporting typos is not of importance. I just believe that "contribution" to a project requires a bit more involvement beyond reporting bugs and typos. This varies depending on the size of the project and how the project is initiated and sponsored. In my case, all projects are not of such a big size and they are not funded by anyone. 

On a related note, you seem to be quite active. Please have a look at [KLPT](https://github.com/sinaahmadi/klpt). I will be more than happy to add your work there as a collaborator, if you intend to address a sub-task and carry out a research question. In the current project, you can also contribute to add Kurmanji to Hunspell. Would that be something of interest to you?

**Comment by rojserbest** [comment]
<div align="center">
بژیت کاک سینا، من هەر مەبەستم ئەوە بوو ئەم ڕایەی خۆت لەسەر PR بڵێیت. بشمبوورە ئەگەر PRـەکانم کەمێک بێمانا بووبن یان شایەنی کاتپێدان نەبووبن، من زۆر شارەزای ئۆپن سۆرس نیم و نەمزانیوە یاسا گشتییەکان چین.

سەبارەت بە کلپتیش، من زمانەوان نیم تا بتوانم کار لە شتی وا بکەم. تەنها دەتوانم هەڵەی زەقی وەک لە https://github.com/sinaahmadi/klpt/pull/12 بدۆزمەوە.

ئەوجا کورمانجیشم زۆر زۆر باش نییە، بەڵام بە ڕای من Rêbera Rastnivîsînê مەکە بە سەرچاوە چونکە زۆربەی یاساکانی باو نین. ئەگەر سەرچاوەیەکی باشت دەوێت کتێبی "Elfabêya kurdî & Bingehên gramera kurdmancî" ببینە، وابزانم بە پیدیئێفیش هەیە ئەگەر کەمێک بگەڕێیت.
</div>

**Pull request closed without merging**
